CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_DISPLAY=y

CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_Z_VDB_SIZE=32

CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y